# Generated by Django 6.0.7 on 2026-07-09 04:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=15, unique=True)),
                ('joined_date', models.DateField(default=django.utils.timezone.now)),
                ('seat_number', models.IntegerField(unique=True)),
                ('shift_plan', models.CharField(choices=[('6_HOURS', '6 Hours Shift'), ('12_HOURS', '12 Hours Shift'), ('FULL_DAY', '24 Hours Full Day')], default='12_HOURS', max_length=20)),
                ('monthly_fees', models.IntegerField(default=1000)),
                ('is_fees_paid', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('is_present', models.BooleanField(default=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.student')),
            ],
        ),
    ]
