# Generated by Django 6.0.7 on 2026-07-09 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_student_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issuedbook',
            name='book',
        ),
        migrations.RemoveField(
            model_name='issuedbook',
            name='student',
        ),
        migrations.DeleteModel(
            name='Book',
        ),
        migrations.DeleteModel(
            name='IssuedBook',
        ),
    ]
