name: Django CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Render
        if: github.ref == 'refs/heads/main'
        run: |
          curl -f "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
